### ISSUE TITLE
Make sure all unsupported module have been removed form the CMS5 sink

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/recipe-kitchen-sink#29]
None of these modules should be on the list.

Module | Status | Notes
-- | -- | --
[bringyourownideas/silverstripe-composer-security-checker](https://packagist.org/packages/bringyourownideas/silverstripe-composer-security-checker) | Dropped | Underlying service has been discontinued.
[composer/installers](https://packagist.org/packages/composer/installers) | Dropped | Composer is more established than Silverstripe CMS.
[cwp-themes/default](https://packagist.org/packages/cwp-themes/default) | Dropped | 
[cwp/cwp](https://packagist.org/packages/cwp/cwp) | CMS5 compatible without support | 
[cwp/cwp-core](https://packagist.org/packages/cwp/cwp-core) | CMS5 compatible without support | 
[cwp/cwp-pdfexport](https://packagist.org/packages/cwp/cwp-pdfexport) | Dropped | 
[cwp/cwp-search](https://packagist.org/packages/cwp/cwp-search) | CMS5 compatible without support | 
[hafriedlander/phockito](https://github.com/hafriedlander/phockito) | Dropped | 
[hafriedlander/silverstripe-phockito](https://packagist.org/packages/hafriedlander/silverstripe-phockito) | Dropped | 
[lekoala/silverstripe-debugbar](https://packagist.org/packages/lekoala/silverstripe-debugbar) | CMS5 compatible without support | Debug bar is a development tool that should not be installed in production.
[silverstripe/activedirectory](https://packagist.org/packages/silverstripe/activedirectory) | Dropped | 
[silverstripe/akismet](https://packagist.org/packages/silverstripe/akismet) | Dropped | The parent library is outdated and they are better alternatives like [UndefinedOffset/silverstripe-nocaptcha](https://packagist.org/packages/undefinedoffset/silverstripe-nocaptcha)
[silverstripe/behat-extension](https://packagist.org/packages/silverstripe/behat-extension) | CMS5 compatible without official support | 
[silverstripe/ckan-registry](https://packagist.org/packages/silverstripe/ckan-registry) | CMS5 compatible without support | 
[silverstripe/comment-notifications](https://packagist.org/packages/silverstripe/comment-notifications) | CMS5 compatible without official support | 
[silverstripe/comments](https://packagist.org/packages/silverstripe/comments) | CMS5 compatible without official support | 
[silverstripe/content-widget](https://packagist.org/packages/silverstripe/content-widget) | CMS5 compatible without support | 
[silverstripe/fulltextsearch](https://packagist.org/packages/silverstripe/fulltextsearch) | CMS5 compatible without support | 
[silverstripe/graphql-devtools](https://packagist.org/packages/silverstripe/graphql-devtools) | CMS5 compatible without official support | 
[silverstripe/html5](https://packagist.org/packages/silverstripe/html5) | Folded back in core | 
[silverstripe/postgresql](https://packagist.org/packages/silverstripe/postgresql) | CMS5 compatible without support | 
[silverstripe/recipe-ccl](https://github.com/silverstripe/recipe-ccl) | CMS5 compatible without support | 
[silverstripe/recipe-solr-search](https://packagist.org/packages/silverstripe/recipe-solr-search) | CMS5 compatible without support | 
[silverstripe/security-extensions](https://packagist.org/packages/silverstripe/security-extensions) | Folded back in core |
[silverstripe/spellcheck](https://packagist.org/packages/silverstripe/spellcheck) | Dropped | 
[silverstripe/sqlite3](https://packagist.org/packages/silverstripe/sqlite3) | CMS5 compatible without support | 
[silverstripe/widgets](https://packagist.org/packages/silverstripe/widgets) | CMS5 compatible without official support | 
[tijsverkoyen/akismet](https://packagist.org/packages/tijsverkoyen/akismet) | Dropped | 
[tractorcow/classproxy](https://packagist.org/packages/tractorcow/classproxy) | CMS5 compatible without official support | 
[tractorcow/silverstripe-proxy-db](https://packagist.org/packages/tractorcow/silverstripe-proxy-db) | CMS5 compatible without official support |
[undefinedoffset/sortablegridfield](https://packagist.org/packages/undefinedoffset/sortablegridfield) | Dropped | [symbiote/silverstripe-gridfieldextensions](https://packagist.org/packages/symbiote/silverstripe-gridfieldextensions) provides equivalent functionality.

## Acceptance criteria
- These modules are all removed from the CMS 5 sink.
- Any references tot hem should be removed from tests.
- (New AC) After merging the recipe-kitchen-sink + recipe-blog PRs, ensure that a new cow plan for 5 does not include cwp/cwp

## PRs
- https://github.com/silverstripe/recipe-kitchen-sink/pull/43
- https://github.com/silverstripe/recipe-blog/pull/42
- https://github.com/silverstripe/developer-docs/pull/283

**Comment by GuySartorelli** [comment]
For CMS 5 compatible versions, we should keep these in the sink until the RC at least, so we can be sure they actually _are_ compatible.

**Comment by emteknetnz** [comment]
Note re silverstripe/behat-extension - it's only in require-dev and isn't part of the regression test.

I'm going to keep it in require-dev so that behat still easily works when running sink on local dev environments

**Comment by emteknetnz** [comment]
Seems like we should also be dropping these?

cwp/starter-theme
cwp/watea-theme
cwp/agency-extensions

?

cwp/agency-extensions in particular because it requires cwp/cwp

**Comment by emteknetnz** [comment]
Some notes I took to work out what actually needs to be updated:

[Supported modules reference](https://docs.silverstripe.org/en/5/project_governance/supported_modules/)

Not in 5 sink:

{x} bringyourownideas/silverstripe-composer-security-checker
- not in 5 sink

{x} cwp-themes/default
- not in 5 sink

{x} cwp/cwp-pdfexport
- not in 5 sink

{x} hafriedlander/phockito
- not in 5 sink

{x} hafriedlander/silverstripe-phockito
- not in 5 sink

{x} lekoala/silverstripe-debugbar
- not in 5 sink

{x} silverstripe/activedirectory
- not in 5 sink

{x} silverstripe/akismet
- not in 5 sink
{x} silverstripe/html5
- not in 5 sink

{x} silverstripe/postgresql
- not in 5 sink

{x} silverstripe/security-extensions
- not in 5 sink

{x} silverstripe/spellcheck
- not in 5 sink

{x} silverstripe/sqlite3
- not in 5 sink

{x} tijsverkoyen/akismet
- not in 5 sink

{x} undefinedoffset/sortablegridfield
- not in 5 sink

---

require-dev or not in cow plan:

{-} tractorcow/silverstripe-proxy-db (as silverstripe/silverstripe-proxy-db)
- required by silverstripe/auditor
- required by silverstripe/fulltextsearch

{-} tractorcow/classproxy
- required by tractorcow/silverstripe-proxy-db

{-} silverstirpe/behat-extension
- required by silverstripe/recipe-testing (require-dev)

{-} silverstripe/graphql-devtools
- requied-dev by root composer.json

{-} composer/installers
- required by silverstripe-themes/simple (which is required by silverstripe/installer)

---

Will be removed by removal of other modules:

{w} cwp/cwp-core
- required by cwp/cwp
- required by silverstripe/recipe-solr-search

{w} cwp/cwp-search
- required by silverstripe/recipe-solr-search

{w} silverstripe/widgets
- required by silverstripe/content-widget

{w} silverstripe/fulltextsearch
- required by silverstripe/recipe-solr-search
- required by cwp/cwp-search

===

A)

Remove from composer.json in silverstripe/recipe-kitchen-sink

{ } silverstripe/recipe-ccl
- required by root composer.json

{ } silverstripe/recipe-solr-search
- required by root composer.json

{ } silverstripe/ckan-registry
- required by root composer.json

{ } cwp/cwp
- required by root composer.json
- required by cwp/agency-extensions

===

B)

Remove from composer.json in silverstripe/recipe-blog:

{ } silverstripe/comment-notifications
- required by silverstripe/recipe-blog

{ } silverstripe/content-widget
- required by silverstripe/recipe-blog

{ } silverstripe/comments
- required by silverstripe/recipe-blog
- required by silverstripe/comment-notifications
Make sure they're not in the plan / upgrade-only / not in changelog

===

C)

Ensure these are not in plan / upgrade-only / not in changelog

{-} cwp/cwp
- required by cwp/agency-extensions (which is still supported)
- I don't think it'll show in plan because parent module isn't a recipe

====

**Comment by maxime-rainville** [comment]
All PRs have been merged.
